### ISSUE TITLE
Sections are unnumbered

### ISSUE THREAD

**Issue by gpoo** [rchurchley/uvicthesis#3]
In the UVic template the sections are explicitly enumerated. However, when using the `uvicthesis class`, only the chapters are enumerated. Sections are unnumbered.

It seems that the `titlesec` package removes the numbers by default.

**Comment by gpoo** [comment]
I narrowed it down, and removing the `titlesec` package solves the issue.

An alternative would be to redefine sections, subsections, and so on. However, it seems too much for such a little gain (like reducing the space in the chapter).

**Comment by rchurchley** [comment]
Thanks for the report! 

This is unintended behaviour of both `uvicthesis` and the `titlesec` package. It appears to be [caused by a recent bug](http://tex.stackexchange.com/questions/299969/titlesec-loss-of-section-numbering-with-the-new-update-2016-03-15) in version 2.10.1 of `titlesec` (released 2016/03/15) but was quickly fixed in 2.10.2 (released 2016/03/21).

Hopefully, you should be good to go if you install the updated version of `titlesec`!

**Comment by gpoo** [comment]
Thank you!
